<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Assessments\" />
      <Folder Include="Characters\NPCs\" />
      <Folder Include="Characters\Students\" />
      <Folder Include="Interfaces\" />
      <Folder Include="Locations\Academy\" />
      <Folder Include="Locations\Outside\" />
    </ItemGroup>

</Project>
